### ISSUE TITLE
Minimum PHP version

### ISSUE THREAD

**Issue by szepeviktor** [Sustainabil-IT/phpstan-higher-order-collections#1]
Please consider supporting (nearly) [the same PHP versions as PHPStan](https://github.com/phpstan/phpstan/blob/39d7903cc773cc7ddc479f0d0a3bf90986c5dafe/composer.json#L6).

and maybe https://twitter.com/szepeviktor/status/1313388920919461890

![kép](https://user-images.githubusercontent.com/952007/95391592-9aae7180-08f7-11eb-8e68-afa1f80c8478.png)

**Comment by szepeviktor** [comment]
`composer require --dev rector/rector`

```php
<?php // rector.php

declare(strict_types=1);

use Rector\Core\Configuration\Option;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $parameters = $containerConfigurator->parameters();
    $parameters->set(Option::SETS, [
        SetList::DOWNGRADE_PHP74,
    ]);
};
```

`vendor/bin/rector process src/`

:)

**Comment by nmokkenstorm** [comment]
The PHP 7.4 requirement was a conscious choice: short closures make life a lot easier within this functional approach to Collection transformations, and official support for 7.3 [ends in a month or so anyways](https://www.php.net/supported-versions.php).

**Comment by szepeviktor** [comment]
> short closures make life a lot easier

Then we disagree :) (see tweet above)

**Comment by nmokkenstorm** [comment]
> Then we disagree :) (see tweet above)

I saw the tweet, you're free to not use short closures even while using this plugin 😄

**Comment by szepeviktor** [comment]
This plugin is so valuable to me that I will make a PHP 7.1+ fork!
