### ISSUE TITLE
Supporting tap()

### ISSUE THREAD

**Issue by szepeviktor** [Sustainabil-IT/phpstan-higher-order-collections#7]
```php
$response = tap($kernel->handle(
    $request = Request::capture()
))->send();
```
https://github.com/laravel/laravel/blob/c66546e75fcbf208d2884b5ac7a3a858137753a3/public/index.php#L47-L55

https://laravel.com/docs/8.x/collections#method-tap

> Call to an undefined method IlluminateSupportHigherOrderTapProxy<mixed>::send().

Could your plugin help me here?

**Comment by szepeviktor** [comment]
I see! 🚰 This is another tap.

https://laravel.com/docs/8.x/helpers#method-tap

What can I do?

**Comment by nmokkenstorm** [comment]
[tap returns a proxy object if you don't pass it a second argument](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Support/helpers.php#L260), which is what happens in your example. Larastan actually has a solution for this [here](https://github.com/nunomaduro/larastan/blob/6b0d6d83e39aaad94907e56b2e35a115eaadb164/src/ReturnTypes/HigherOrderTapProxyExtension.php), that'd probably solve your problem?

**Comment by szepeviktor** [comment]
Thank you for your guidance!
I'm not a developer.

The result for `public/index.php` is as follows.

```php
/** @var \Illuminate\Foundation\Application */
$app = require_once __DIR__.'/../bootstrap/app.php';

/** @var \Illuminate\Contracts\Http\Kernel */
$kernel = $app->make(Kernel::class);

$response = tap($kernel->handle(
    $request = Request::capture()
))->send();

$kernel->terminate($request, $response);
```
